=== LadDevendra/WebProgramming_FullStack/XML XSD and its parcing/HW4.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="ProductName">
	<xsd:simpleType>
	    <xsd:restriction base="xsd:string">
	     	 <xsd:pattern value="[A-Z][a-zA-Z0-9]*(\s[a-zA-Z0-9]*)*"/>
	    </xsd:restriction>
	 </xsd:simpleType>
</xsd:element>
<xsd:element name="ProductDescription">
	<xsd:simpleType>
	    <xsd:restriction base="xsd:string">
	     	 <xsd:pattern value="[A-Z][a-zA-Z0-9]*(\s[a-zA-Z0-9]*)*"/>
	    </xsd:restriction>
	 </xsd:simpleType>
</xsd:element>
<xsd:element name="ReleaseDate" type="xsd:date"/>
<xsd:element name="ProductCost">
  <xsd:complexType>
    <xsd:simpleContent>
      <xsd:extension base="xsd:double">
        <xsd:attribute name="currency" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
</xsd:element>

<xsd:element name="CompanyName">
	<xsd:simpleType>
	    <xsd:restriction base="xsd:string">
	     	 <xsd:pattern value="[A-Z][a-zA-Z]*(\s[A-Z][a-zA-Z]*)*"/>
	    </xsd:restriction>
	 </xsd:simpleType>
</xsd:element>
<xsd:element name="CompanyAddress">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="StreetName">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[0-9]*\_[A-Z][a-z]*(\s[A-Z][a-zA-Z]*)*"/>
					</xsd:restriction>
  				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="City">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[A-Z](([a-z])*)"/>
					</xsd:restriction>
  				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="ZipCode">
				<xsd:simpleType > 
					<xsd:restriction base="xsd:integer">
						<xsd:minExclusive value="11111"/>
						<xsd:maxInclusive value="99999"/> 
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Country">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="([A-Z])*"/>
					</xsd:restriction>
  				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="Company">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="CompanyName"/>
			<xsd:element ref="CompanyAddress"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>


<xsd:element name="Product">
	<xsd:complexType>
		<xsd:sequence>	
			<xsd:element ref="ProductName"/>
			<xsd:element ref="ProductDescription"/>
			<xsd:element ref="ReleaseDate"/>
			<xsd:element ref="ProductCost"/>
			<xsd:element ref="Company"/>
		</xsd:sequence>				
	</xsd:complexType>
</xsd:element>

<xsd:element name="root">
	<xsd:complexType>
        <xsd:sequence>
		<xsd:element ref="Product"  maxOccurs="10"/>
        </xsd:sequence>	
	</xsd:complexType>
</xsd:element>
</xsd:schema>

=== LadDevendra/WebProgramming_FullStack/XML XSD and its parcing/HW4.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HW4.xsd">
<Product>
	<ProductName>Mackbook</ProductName>
	<ProductDescription>Mackbook Pro is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2016-11-10 </ReleaseDate>
	<ProductCost currency="dollars">1150.00</ProductCost>
	<Company>
		<CompanyName>Apple</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>USA</Country>
		</CompanyAddress>
	</Company>
</Product>	
<Product>
	<ProductName>Galaxy edge</ProductName>
	<ProductDescription>S6 Pro is a strong and powerful phone</ProductDescription>
	<ReleaseDate> 2016-11-11 </ReleaseDate>
	<ProductCost currency="dollars">75.00</ProductCost>
	<Company>
		<CompanyName>Samsung</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>NORTHKOREA</Country>
		</CompanyAddress>
	</Company>
</Product>	
<Product>
	<ProductName>Yoga</ProductName>
	<ProductDescription>Yoga is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2015-11-10 </ReleaseDate>
	<ProductCost currency="dollars">90.00</ProductCost>
	<Company>
		<CompanyName>Lenovo</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>USA</Country>
		</CompanyAddress>
	</Company>
</Product>	
<Product>
	<ProductName>MicroMax 601</ProductName>
	<ProductDescription>Max is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2012-11-10 </ReleaseDate>
	<ProductCost currency="dollars">1000.00</ProductCost>
	<Company>
		<CompanyName>MicroMax</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>INDIA</Country>
		</CompanyAddress>
	</Company>
</Product>
<Product>
	<ProductName>MicroMax 541</ProductName>
	<ProductDescription>Max is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2005-11-10 </ReleaseDate>
	<ProductCost currency="dollars">500.00</ProductCost>
	<Company>
		<CompanyName>MicroMax</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>INDIA</Country>
		</CompanyAddress>
	</Company>
</Product>
<Product>
	<ProductName>MicroMax 601</ProductName>
	<ProductDescription>Max is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2009-11-10 </ReleaseDate>
	<ProductCost currency="dollars">700.00</ProductCost>
	<Company>
		<CompanyName>MicroMax</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>INDIA</Country>
		</CompanyAddress>
	</Company>
</Product>
<Product>
	<ProductName>Yoga 456</ProductName>
	<ProductDescription>Yoga is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2014-11-10 </ReleaseDate>
	<ProductCost currency="dollars">680.00</ProductCost>
	<Company>
		<CompanyName>Lenovo</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>USA</Country>
		</CompanyAddress>
	</Company>
</Product>	
<Product>
	<ProductName>Yoga X1</ProductName>
	<ProductDescription>Yoga is a strong and powerful laptop</ProductDescription>
	<ReleaseDate> 2016-11-10 </ReleaseDate>
	<ProductCost currency="dollars">799.00</ProductCost>
	<Company>
		<CompanyName>Lenovo</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>USA</Country>
		</CompanyAddress>
	</Company>
</Product>	
<Product>
	<ProductName>Galaxy S6</ProductName>
	<ProductDescription>S6 Pro is a strong and powerful phone</ProductDescription>
	<ReleaseDate> 2016-11-11 </ReleaseDate>
	<ProductCost currency="dollars">75.00</ProductCost>
	<Company>
		<CompanyName>Samsung</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>NORTHKOREA</Country>
		</CompanyAddress>
	</Company>
</Product>	
<Product>
	<ProductName>Iphone6</ProductName>
	<ProductDescription>Iphone6 Pro is a strong and powerful Phone</ProductDescription>
	<ReleaseDate> 2016-11-10 </ReleaseDate>
	<ProductCost currency="dollars">800.00</ProductCost>
	<Company>
		<CompanyName>Apple</CompanyName>
		<CompanyAddress>
			<StreetName>1_Infinite Loop</StreetName>
			<City>Cupertino</City>
			<ZipCode>95014</ZipCode>
			<Country>USA</Country>
		</CompanyAddress>
	</Company>
</Product>	
</root>
